### ISSUE TITLE
IgcGrid - maximizing the browser window after scrolling to the right caused disappearing columns and changing column order unexpectedly

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-webcomponents#1019]
## Description  

When I maximize the browser window after scrolling the `<igc-grid>` to the right, it caused disappearing columns and changing column order unexpectedly.

## Steps to reproduce  

1. Make a web page with an `<igc-grid>` component including columns of  `ID`, `Name`, `Age`, `Role`, and an extra 5 columns. Be sure to make all columns have a fixed width of 100px.
2. Run it in a web browser.
3. Shrink the width of the browser window.
4. Scroll to the end of the right of the scrolling area of the `<igc-grid>`.
5. Click the maximize button of the browser.

## Result  
- The `ID` column has disappeared. 
- The `Name` and `Age` columns were moved to the end of the right side. 
- The `Role` column has been duplicated, and one appeared on the right side.

## Expected result  
Nothing strange should happen.

## Attachments  
See also the video below.

https://github.com/IgniteUI/igniteui-webcomponents/assets/102948935/67a8cf19-b206-4508-8762-656f2291962d

The project that can reproduce this issue is below.

[📦c-00234580-web-app1.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/13883435/c-00234580-web-app1.zip)

**Comment by TFujisawa123** [comment]
I am running into this issue as well.
Are there any plans to fix it?

**Comment by dkamburov** [comment]
We already have a fix, please stay tuned for the next official release. The plan is to be out very soon. There is currently a [beta](https://www.npmjs.com/package/igniteui-webcomponents-grids/v/4.7.2-beta.2) and you can even try it out.

**Comment by jsakamotoIGJP** [comment]
@dkamburov Thanks, Deyan!
I verified that the issue had gone away on the v.4.7.2-beta.2 package.

However, the position of the horizontal scrollbar and the actual view was unmatched after restoring the browser window size from the maximized state. (Please see the video I attached)

https://github.com/IgniteUI/igniteui-webcomponents/assets/102948935/1873ed37-65b6-40cf-8216-b319ce4521cf

I'd appreciate it if you could also address this small problem.
But if it takes time to fix that second minor issue, we strongly agree with postponing handling the second one since so many customers are waiting to fix the column order problem.

**Comment by dkamburov** [comment]
@jsakamotoIGJP I logged it as a separate issue and we'll investigate it, but I don't think it will make it to the upcoming release.

**Comment by jsakamotoIGJP** [comment]
@dkamburov Sure, no problem. Thank you for creating the issue #1116!
