### ISSUE TITLE
Calendar: Placeholder labels in the header are redundant

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#1022]
## Description  
Currently, the calendar shows placeholder labels in the header when no date is selected. This behavior is different than the one in Ignite UI for Angular where the current year and date is show in the respective areas of the header.

What should the correct behavior be? IMO, the header should have a more meaningful default labels that are more descriptive/show useful information.

Here's a screenshot of the default state of the calendar as compared to the implementation in Ignite UI for Angular:

![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/4118303/32728043-bd91-49c4-b72f-35413f73e8de)

**Comment by simeonoff** [comment]
@sdimchevski Your two cents on this question will be appreciated.

**Comment by pmoleri** [comment]
"Selected date" does it even make sense?

**Comment by simeonoff** [comment]
> "Selected date" does it even make sense?

We've discussed it with Svilen, even though he hasn't replied here. We've decided that we want to have the current date instead of the `Selected date` placeholder in case no date has been selected.
