### ISSUE TITLE
Calendar: Switching selection modes keeps selected dates

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#1027]
## Description  
If we make a selection in a calendar with `selection` set to `multiple` and then switch the `selection` mode to `range`, the selected value is transformed into a `range` of dates between the `start` and `end` dates of the previously selected dates in the `multiple` selection mode. Changing the `selection` mode back to `multiple` restores the previously selected dates in the days view.

## Question
Should this behavior be implemented in Ignite UI for Angular the way it's implemented here?

**Comment by rkaraivanov** [comment]
@simeonoff
Short answer: no.

Going over the specification, I could not find anything that prescribes such behavior.
After #1200, the calendar has the same behavior as its Angular counterpart.
