### ISSUE TITLE
Reset and Submit buttons inside Form don't work when there's anything more complex than plain text inside the buttons.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-webcomponents#1087]
## Description  
Reset and Submit do not trigger if the button has any element in its label content, for example a span:

```
<igc-form id="form">
...
                    <igc-button type="reset"><span>Reset</span></igc-button>
                    <igc-button type="submit"><span>Submit</span></igc-button>
</igc-form>
```
Any click inside the span will not trigger the related action. Reason is this check here: https://github.com/IgniteUI/igniteui-webcomponents/blob/master/src/components/form/form.ts#L187 , since a span itself is not a control that submits/resets.

## Steps to reproduce  

1. Run the sample: 
[form-with-buttons.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/14406039/form-with-buttons.zip)

2. Click on Reset/Submit inside the buttons

## Result  
Nothing happens. If you manage to click outside the span but still inside the button, then it will work though.

## Expected result  
It should work no matter where in the button you click.

**Comment by rkaraivanov** [comment]
The `igc-form` component is deprecated since v4.4.0.
The native `form` element should be used instead, and any FACE components (buttons included) should
work inside its context.

**Comment by MayaKirova** [comment]
@rkaraivanov @georgianastasov In that case should the documentation around it be deprecated as well for wc/react/blazor:
https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/form
https://www.infragistics.com/products/ignite-ui-react/react/components/inputs/form
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/form

**Comment by rkaraivanov** [comment]
@MayaKirova 
@georgianastasov 

Yes, please open an issue in the documentation/samples repository as I'm closing this one.
