### ISSUE TITLE
igc-slider: Bound slider updates variable value to negative number

### ISSUE THREAD

**Issue by GrblackStar** [IgniteUI/igniteui-webcomponents#1109]
## Description  
Two-way bound slider can change the value of the bound variable to negative numbers when the user continues sliding after reaching 0

## Steps to reproduce  

1. Download and run the provided sample
2. drag the slider to the LEFT to change it's value. The value of the bound variable is shown on the left

## Result  
The value of the bound variable is less than 0
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/86851411/8f26e2d9-0c24-43e8-a078-b5770b0b2a5a)

## Attachments  
[Web_Components_Sample_Slider.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/14651347/Web_Components_Sample_Slider.zip)

**Comment by rkaraivanov** [comment]
Already fixed in #1049
Will be included in next release.
