### ISSUE TITLE
Arrows aren't working on the DateTimeInput.

### ISSUE THREAD

**Issue by imincheva** [IgniteUI/igniteui-webcomponents#1171]
Arrows aren't working on the DateTimeInput.

https://github.com/IgniteUI/igniteui-webcomponents/assets/116892553/b15a2dc1-6bce-45b6-b64f-022c98ad3a51

_Originally posted by @imincheva in https://github.com/IgniteUI/igniteui-webcomponents/issues/1086#issuecomment-2065902823_

**Comment by simeonoff** [comment]
@imincheva Can you pull the latest master and check again?
