### ISSUE TITLE
Enhancing Web Components Form Validation

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/igniteui-webcomponents#1195]
Here is a sample that demonstrate the current way to implement Web Components form with validation: [Web Components Validation](https://github.com/Marina-L-Stoyanova/FormsBuilder/tree/main/All%20components%20samples/WebComponents%20validation)

We should consider:
1. In-Component Validation:
     > Implement validation logic directly within the Web Components that can be used in a Form(igc-input, igc-textarea, igc-select and ect.). This approach encapsulates validation rules and keeps them self-contained.
     > Validate input data as users interact with the form elements (e.g., on blur or input change events).
2. Displaying Validation Messages:
   > Show validation messages when input is invalid. 
3. Slot Considerations:
    > Evaluate whether to use existing slots (like helper-text) or create a dedicated slot (e.g., validation-message) for displaying validation feedback. (Using a separate slot allows flexibility in styling and positioning validation messages.)

**Comment by rkaraivanov** [comment]
> We should consider:
> 
> 1. In-Component Validation:
>    > Implement validation logic directly within the Web Components that can be used in a Form(igc-input, igc-textarea, igc-select and ect.). This approach encapsulates validation rules and keeps them self-contained.

This is already covered by the existing form associated components.

> Displaying Validation Messages
> Slot Considerations

This definitely merits further exploration and potential integration into the library. In my opinion, dedicating a distinct slot solely for error messages seems advantageous. We'll begin to consider these aspects and aim to have a preliminary implementation shortly.
