### ISSUE TITLE
Date picker with no value

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#1205]
## Description  
I am trying to clear the value of the `date-picker` or to set it to nullable data. 

## Steps to reproduce  
Use code like this:

```ts
@state()
private undefinedDate?: Date;

...

<igc-date-picker .value=${this.undefinedDate}
        selectedValueChanged=${(_s: IgcDatePickerComponent, e: IgcSelectedValueChangedEventArgs) => this.undefinedDate = e.newValue}>
</igc-date-picker>
```

or like this:

```ts
@state()
private definedDate?: Date = new Date();
...
<igc-date-picker .value=${this.definedDate}
        selectedValueChanged=${(_s: IgcDatePickerComponent, e: IgcSelectedValueChangedEventArgs) => this.definedDate = e.newValue}>
</igc-date-picker>
```

## Result  
In first case application throws an error - ` Cannot read properties of undefined (reading 'getHours')`.
In second case if I click on clear value button the value of the date picker becomes 01.01.0001 instead of `undefined` or `null`.

## Expected result  
Data picker should be able to accept nullable values as its value.

**Comment by IvanKitanov17** [comment]
@wnvko Can you please tell me if you are referring to the deprecated igc-date-picker that is imported from igniteui-webcomponents-inputs? Since I am not able to reproduce the issue with the new one that has been newly added. Also I believe that the IgcSelectedValueChangedEventArgs is part of the API of the deprecated one and not the newer one.

**Comment by wnvko** [comment]
@IvanKitanov17 
I took this sample from the documentation [Date picker](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/editors/date-picker), and modified it [here](https://codesandbox.io/s/stupefied-ellis-fq7l5q?file=/src/index.ts). I am not sure which date picker is new and which one is old, but in the sample above if you click clear icon on the date picker the value of the `date` variable becomes 01.01.0001.

![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/5990334/da81f839-86fb-45fd-87a6-bd4d8796d5de)

**Comment by IvanKitanov17** [comment]
@wnvko The one from the documentation is the old one, which is not part of this repository. It is going be deprecated and replaced with the newly added one, I was also told that all the issues for the old one have been discarded, due to the upcomming release of the new igc-date-picker.

**Comment by wnvko** [comment]
Ok, then if this issue does not reproduce in the new one we can safely close it.
