### ISSUE TITLE
Slider: Theme Issues

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#1213]
1. The track should have 4px radius
2. The tickmarks should start right under the end of the track. 
<img width="628" alt="Screenshot 2024-05-15 at 14 29 34" src="https://github.com/IgniteUI/igniteui-webcomponents/assets/143710956/3aa6a0c6-cffb-4dfa-abd9-a7f114179ddd">

3.Тhe "Discrete Regions" should start from 0 as in the Handoff

<img width="691" alt="Screenshot 2024-05-15 at 17 11 34" src="https://github.com/IgniteUI/igniteui-webcomponents/assets/143710956/740d3ce7-7408-424e-990a-31159cd30e07">

4. The focus border of the thumb should be 3px

5. Тhe triangle of the label tooltip should have 12px height
@andiesm813  please, check the comments and also, please check the behaviour of the Hover and Focus states - whether each element should have these states separately or when on Hover or Focused the whole component should be in that state.

_Originally posted by @sbayreva in https://github.com/IgniteUI/igniteui-webcomponents/issues/1134#issuecomment-2112293500_

Comment from Andie:

@sbayreva
All your comments (1-4) are good. About https://github.com/IgniteUI/igniteui-webcomponents/issues/1 (radius of the track), it was also not implemented in Angular (from what i'm seeing).

About the hover and focus states, the current behavior in WC is the same as in the Angular component. Track and track base do hover together, but the thumb hovers separately, only when hovered on the thumb. So IMO it's all good as implemented now.

**Comment by didimmova** [comment]
@sdimchevski @andiesm813 We discussed that the slider ticks and thumb are positioned correctly the way they're positioned now. Also having steps on 0 and 100 IMO are unnecessary but if you insist on having them, it's for a different issue, that would probably not be handled by our team.
