### ISSUE TITLE
[Bug]: Dropdown - White edges appear around the dropdown list in dark mode

### ISSUE THREAD

**Issue by SisIvanova** [IgniteUI/igniteui-webcomponents#1247]
### Which component(s) are affected?

Dropdown

### Description

White edges can be seen around the dropdown list in the dark variants of all themes. 

<img width="191" alt="Screenshot 2024-06-12 at 4 36 04 PM" src="https://github.com/IgniteUI/igniteui-webcomponents/assets/59446295/cb96c9bd-fc42-4456-8cac-6a6ee0152d4f">

### Reproduction

1. Open the dropdown story
2. Switch to dark variant
3. Open the dropdown and observe the edges of the list

### Workaround

Additional border-radius should be applied to the popover.

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

All

### Browser/OS/Node environment

All

**Comment by rkaraivanov** [comment]
I see you've also logged it. I'll link mine issue here as well
#1244
