### ISSUE TITLE
[IgcGrid] - How to conditionally prevent editing on certain cells?

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-webcomponents#1342]
How to conditionally prevent editing on certain cells?

**Comment by RivaIvanova** [comment]
Hi @mddifilippo89,

If you require to cancel the cell from entering edit mode, I could suggest using the `cellEditEnter` event and setting its `cancel` property to `true` if a certain condition is met. For example:

```ts
private grid: IgcGridComponent;

constructor() {
    this.grid = document.getElementById('grid') as IgcGridComponent;
    ...
    this.grid.addEventListener('cellEditEnter', (event) => {
        const args = event as CustomEvent<IgcGridEditEventArgs>;
        if (args.detail.column.field === 'ContactName') {
            args.detail.cancel = true;
        }
        if (args.detail.column.field === 'CompanyName' && args.detail.cellID.rowIndex % 2 === 0) {
            args.detail.cancel = true;
        }
    });
}
```
The first part will prevent all cells from the 'ContactName' column from entering edit mode, whereas the second part will prevent only the even cells from the 'CompanyName' column from entering edit mode.
![igcGrid cellEditEnter](https://github.com/user-attachments/assets/a22a3aee-1077-42f1-852b-3ddf6beabf9c)


[Here](https://codesandbox.io/p/sandbox/loving-lalande-vnsfzm) could be found a small sample that demonstrates my suggestion. I hope it helps achieve your requirements.
