### ISSUE TITLE
[IgcCheckbox] - Tick color css not working

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-webcomponents#1343]
How to change tick color within a tree?

eg. https://codesandbox.io/p/sandbox/cranky-jang-gdr6f8

igc-checkbox {
  --tick-color: green;
  --fill-color: red;
}

igc-tree {

  --tick-color: green;
  --fill-color: red;
}

**Comment by mddifilippo89** [comment]
In the following example, tick-color doesn't appear to be modifiable on the tree, but fill-color is. 
https://codesandbox.io/p/sandbox/cranky-jang-gdr6f8

eg.
--ig-checkbox-tick-color

**Comment by mddifilippo89** [comment]
the tick color is modifiable with a standalone checkbox
https://codesandbox.io/p/sandbox/cocky-bose-8j5vtn

**Comment by simeonoff** [comment]
I cannot reproduce in the master branch. It seems that either the react components wrap an old version of Ignite UI for Web Components where the bug existed, or the react wrappers somehow parse and modify the styles before bundling. I believe the latter is more likely.
