### ISSUE TITLE
[Bug]: PivotGrid is not loading properly due to PivotGridConfiguration

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-webcomponents#1368]
### Description

Uncaught TypeError: Cannot read properties of null (reading 'enabled')
at new Wc (combined.js:43561:413)
at get pivotConfiguration1 (index.ts:18:39)

The issue is currently presented on our staging samples browser - pivot features sample. 

Sample Location:
https://github.com/IgniteUI/igniteui-wc-examples/tree/vnext/samples/grids/pivot-grid/features

Running example:
https://staging.infragistics.com/webcomponents-demos/grids/pivot-grid/features

Issue:
![image](https://github.com/user-attachments/assets/10dd8970-a6d3-432a-85e1-28f6673fcedb)

### Reproduction

[As shown above](https://staging.infragistics.com/webcomponents-demos/grids/pivot-grid/features)

[features.zip](https://github.com/user-attachments/files/16784710/features.zip)

### Workaround

No workaround found.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

"igniteui-webcomponents-*": "5.0.0-beta.1"
@infragistics/igniteui-webcomponents-core": "24.1.35

### Browser/OS/Node environment

Edge

**Comment by MayaKirova** [comment]
Seems to be an angular issue related to PivotDateDimension in particular: https://github.com/IgniteUI/igniteui-angular/issues/14705

**Comment by rkaraivanov** [comment]
Closed via https://github.com/IgniteUI/igniteui-angular/pull/14707
