### ISSUE TITLE
Input bound to local variable does not reset correctly

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#1386]
### Which component(s) are affected?

Input

### Description

Resetting an input in a form does not reset to initial value. Initial value of the input is bound to a variable. The variable is initialized via call to an end point.

### Reproduction

1. Add variable and initialize it via call to an end point.
2. Add form.
3. Inside the form add an `igc-input` and bound its value to the variable.
4. Add `reset` type button in the form.
5. Run application.
6. Change the input value.
7. Click the reset button.

Code should look like this:
```html
  constructor() {
    super();
    northwindABService.getCustomerDto('ALFKI').then(data => this.customer = data);
  }

  @state()
  private customer?: CustomerDto;

  render() {
    return html`
      <form @submit="${this.submit}" class="column-layout form">
        <igc-input value="${ifDefined(this.customer?.customerId)}" name="customerId"></igc-input>
        <igc-button variant="outlined" type="reset" class="button">Reset<igc-ripple></igc-ripple>
      </form>
    `;
  }
```

### Workaround

Not workaround but if I use `input` reset works correctly. Also, if I bound the `igc-input` to a constant reset works correctly.

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

4.11.1

### Browser/OS/Node environment

All

**Comment by rkaraivanov** [comment]
Can you provide a sample isolating the issue? I cannot seem to reproduce it

**Comment by wnvko** [comment]
Here is a sample showing this behavior - https://github.com/wnvko/web-components-input-issue
