### ISSUE TITLE
IgbSwitch fires onclick event twice

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#1425]
## Description  
`IgbSwitch` fires twice the `onclick` event.

## Steps to reproduce  

Add an `IgbSwitch` to the view and handle its `onclick` event like this:
```razor
<IgbSwitch @onclick="@HandleOnClick"></IgbSwitch>

@code {
    private void HandleOnClick()
    {
        Console.WriteLine("onclick was fired");
    }
}
```
## Result  
Observe the console output - on each click on the switch `onclick` fires twice.

## Expected result  
Clicking on the switch should fire `onclick` event once.

_Note: this happens in version 24.1.52_

**Comment by dkamburov** [comment]
[e609ac2c-4639-4e0e-9c02-d29f0fb24469.zip](https://github.com/user-attachments/files/17305146/e609ac2c-4639-4e0e-9c02-d29f0fb24469.zip)
Attaching the sample as well
