### ISSUE TITLE
[Bug]: Number type input does not make form invalid

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#1426]
### Which component(s) are affected?

Input

### Description

Create a form and add inside `igc-input` with `type` set to `number`. Make the input required. Start the application, then:
1. Submit the form without filling the required input.
2. Add some value in the required input, then delete it and submit the form.

In first scenario form is submitted even though it is not in valid state. If you check `form.checkValidity()` it returns `true`.
In second scenario the input does not paint its in error state and the form's state is still valid.

### Reproduction

Here is a sample showing this behavior - https://codesandbox.io/p/sandbox/green-framework-p4y5pl

### Workaround

Did not try to find a workaround.

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

~4.11.1

### Browser/OS/Node environment

All

**Comment by rkaraivanov** [comment]
Fixed by #1254
