### ISSUE TITLE
[Bug]: DatePicker throws error when the data is string

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/igniteui-webcomponents#1467]
### Which component(s) are affected?

Date picker

### Description

When the Date comes from  an endpoint in string format , DatePicker throws error.

### Reproduction

In a forms scenario where the form is bound to an endpoint with Date fields, attempting to run the application result in the following error. 
![image](https://github.com/user-attachments/assets/5aa54bc5-55c1-4ce1-9f7a-4a8871ea95b4)

### Workaround

no

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

latest

### Browser/OS/Node environment

Chrome

**Comment by rkaraivanov** [comment]
@Marina-L-Stoyanova 
Do you have a sample reproducing the issue?

**Comment by Marina-L-Stoyanova** [comment]
@rkaraivanov Here is the sample: 
[webComponents_datepicker.zip](https://github.com/user-attachments/files/17647688/webComponents_datepicker.zip)
