### ISSUE TITLE
[Bug]: igc-combo: It seems to repeat select an item and rendering infintely after autofill works in Edge.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-webcomponents#1497]
### Which component(s) are affected?

Combo

### Description

After autofill which fills all the textboxes all at once works in Edge and an igc-combo's data is set in accordance with the other igc-combo's selection (meaning, cascading), the cascaded igc-combo gets unresponsive.

### Reproduction

1. Start the application, using Edge.
2. Type any text in every input text boxes. Choose any item in each igc-combo.
3. Click the "Submit" Button.
4. Click the first text box on the page. Autofill candidates are displayed. Choose one which autofills the both text boxes all at once.
5. Open the dropdown of the Country igc-combo. Choose any item other than the selected one.
6. Open the dropdown of the City igc-combo. Try choosing any item.
-> The City igc-combo gets unresponsive.``

For your reference, I also attached a recording which demonstrates the issue. From around 0:00:21, I'm trying clicking one of the items in the igc-combo dropdown, but igc-combo doesn't respond to the clicks.

[c00240339-wcapp1.zip](https://github.com/user-attachments/files/17942076/c00240339-wcapp1.zip)
[C_00240171_BlazorApp1_Recording1.zip](https://github.com/user-attachments/files/17942077/C_00240171_BlazorApp1_Recording1.zip)

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

"igniteui-webcomponents": "^5.1.2"

### Browser/OS/Node environment

Browser: Edge 131.0.2903.70 (Official Build) (64-bit) (*Note that this issue occurs only when Edge's "autofull all at once" is invoked.)
OS: Windows 11 (not tried the other OS)
Node version: 20.17.0
npm version: 10.8.1

**Comment by rkaraivanov** [comment]
@norikois 
Really interesting scenario in Edge. It seems autofill invokes the combo main input focus handler while filling the input, like a lot, which in turn, triggers the virtualizer resize observer(?!) leading to the reported scenario.

Anyway, I've tested your sample with the build from #1464 where there is some internal refactoring of the combo component, and it seems to fix this particular issue. Once it lands in master, we will release it with the next version of the library.
