### ISSUE TITLE
Avatar with slotted icon: icon size is not correct

### ISSUE THREAD

**Issue by didimmova** [IgniteUI/igniteui-webcomponents#1500]
### Which component(s) are affected?

Avatar

### Description

When having an avatar with slotted icon, the icon is changing it's size along with the avatar size, but it should remain the same (24px for material, bootstrap and fluent, 14px for indigo) in all sizes.

The issue is present in all themes, except for indigo.

In the examples bellow there are the different sizes of the avatar, where the left ones are angular avatars, the right ones are WC avatars.

<img width="522" alt="Screenshot 2024-12-02 at 13 11 57" src="https://github.com/user-attachments/assets/053809d2-a5c3-499a-a509-ffcfd5bfe8aa">
<img width="540" alt="Screenshot 2024-12-02 at 13 12 01" src="https://github.com/user-attachments/assets/d53ab31e-31c3-4ff3-9398-1e575c781190">
<img width="555" alt="Screenshot 2024-12-02 at 13 12 04" src="https://github.com/user-attachments/assets/c03e7368-ccde-47bd-b578-fd78f5b0aa4d">

Here's a link to the [Material UI Kit](https://www.figma.com/design/rPQFTo4Ktj4tMDncnwPtHk/Indigo.Design-UI-Kit-for-Material-1.5?node-id=3249-154758&node-type=canvas&t=1oGdRjYrLG9Bs8yd-0)

### Reproduction

1. Open Avatar Story
2. Slot an icon in the avatar
3. Change sizes and observe

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

all

### Browser/OS/Node environment

all

**Comment by SisIvanova** [comment]
While working on this issue, I noticed that the avatar colors differ from the UI Kits so I fixed them here - https://github.com/IgniteUI/igniteui-theming/pull/365
