### ISSUE TITLE
Dropdown Scroll Strategy Doesn't Work

### ISSUE THREAD

**Issue by didimmova** [IgniteUI/igniteui-webcomponents#1512]
### Which component(s) are affected?

Dropdown

### Description

It seems like changing the scroll strategy of the dropdown, using the controls in the storybook, doesn't work.

### Reproduction

1. Open Dropdown sample in storybook
2. Change between the options of the scrollstrategy
3. Observe

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

all

### Browser/OS/Node environment

all

**Comment by rkaraivanov** [comment]
@didimmova 
Can you clarify if this is for the default dropdown sample or in general?
The only sample that has an overflowing story container is the Dropdown > Overflow where the options do work since there is an actual scrollable parent

**Comment by didimmova** [comment]
> @didimmova Can you clarify if this is for the default dropdown sample or in general? The only sample that has an overflowing story container is the Dropdown > Overflow where the options do work since there is an actual scrollable parent

In my case I set the scroll strategy to block and the dropdown is still scrollable

https://github.com/user-attachments/assets/85c67549-d29a-49fd-83e1-5335a95a9bd2

**Comment by didimmova** [comment]
so the issue is in angular then?


https://github.com/user-attachments/assets/fa8bcc67-6fc4-4982-9a9d-a03c7000a2c6

**Comment by rkaraivanov** [comment]
There is an issue. Whether it is in the angular position strategy and/or its interaction with the web component dropdown scroll handler for the top layer I cannot say right away. Open a bug report in the angular repository with this sample as the reproduction.
