### ISSUE TITLE
[DataGrid] Localization string of Column_Options_Summary_Average is applied to Column_Options_Summaries

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-webcomponents#246]
## Description  
[DataGrid] Localization string of Column_Options_Summary_Average is applied to Column_Options_Summaries.

## Steps to reproduce  

1. npm install and npm start. Open http://localhost:8080 in a browser.
2. Click the vertical three-dot icon in one of the headers to open the column options.
-> See the place where "Summaries" should be.

## Result  
"[JP] Average" is displayed.
![SCSK-Q3-app1-screenShot1](https://user-images.githubusercontent.com/33947244/154881060-7f48b30a-508c-4d51-b098-8e13a6effa4a.png)

## Expected result  
"[JP]Summaries" should be displayed.

## Attachments  
[SCSK-Q3-app1.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/8105806/SCSK-Q3-app1.zip)

**Comment by mddifilippo89** [comment]
This issue was fixed internally, see 273782. This will be available in an upcoming release. Marking this closed
