### ISSUE TITLE
I don't seem to be able to see the focus border on the checkbox and the radio, the way it shows for the switch.

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#298]
I don't seem to be able to see the focus border on the checkbox and the radio, the way it shows for the switch.
<img width="265" alt="Screenshot 2022-03-16 at 16 29 04" src="https://user-images.githubusercontent.com/1702064/158613189-4b626f0a-0db6-46f0-aeec-fdd7679a3cfd.png">
<img width="152" alt="Screenshot 2022-03-16 at 16 28 55" src="https://user-images.githubusercontent.com/1702064/158613204-684808e5-0b6f-481d-bb45-811d0f78de49.png">

_Originally posted by @StefanIvanov in https://github.com/IgniteUI/igniteui-webcomponents/pull/293#pullrequestreview-911727353_

**Comment by simeonoff** [comment]
@StefanIvanov Mind you, this doesn't work the way it should be in the switch either. The border should only show when receiving focus with the keyboard, but not when the focus is triggered by mouse click.

**Comment by StefanIvanov** [comment]
> @StefanIvanov Mind you, this doesn't work the way it should be in the switch either. The border should only show when receiving focus with the keyboard, but not when the focus is triggered by mouse click.

Yes I was trying with both mouse and keyboard, but neither of them made it possible for me to see the focus border.
