### ISSUE TITLE
Chip does not show icons

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#327]
Add a chip to the page and set its `Selectable` and/or `Removable` to true like this:
```
<igc-chip selectable removable>TEST</igc-chip>
```
Run the project and click on the chip to select it. There is no remove, nor select icons.
![image](https://user-images.githubusercontent.com/5990334/162959546-68fd8120-4364-4156-932c-e0dbfefeeeca.png)

_Note: I can add the icons as shown [here](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/icon#adding-icons), but this should come out-of-the-box when `selectable` or `removable` are set_

**Comment by mddifilippo89** [comment]
Please modify/fork this sample to demonstrate the issue.
https://codesandbox.io/s/github/IgniteUI/igniteui-wc-examples/tree/vnext/samples/inputs/chip/size

**Comment by rkaraivanov** [comment]
@wnvko 
Can you what exactly is not working? Is the icon itself missing (i.e. not loaded from the internal collection) or the `igc-icon` is not registered as a custom element in the browser?

**Comment by wnvko** [comment]
The issue is icon does not appear out-of-the-box. I expect that when I set `removable` I will end up with a chip with remove icon without registering any icons in the application. This should happen in the component. This is what is generated:
![image](https://user-images.githubusercontent.com/5990334/163134309-1333c7bd-2173-4808-892b-575f3e19566b.png)
Everything is there except the icon's SVG. It is not registered but it should be.
