### ISSUE TITLE
Selected chip is misaligned

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#328]
Add several chips to the page. Set `selectable`, start the application and select a chip. Selected chip moves upward.
![image](https://user-images.githubusercontent.com/5990334/162968825-53eb7506-79fb-42fc-b21b-9abf6f3b842a.png)

**Comment by mddifilippo89** [comment]
Please modify/fork this sample to demonstrate the issue. 
https://codesandbox.io/s/github/IgniteUI/igniteui-wc-examples/tree/vnext/samples/inputs/chip/size

**Comment by mddifilippo89** [comment]
This appears related to https://github.com/IgniteUI/igniteui-webcomponents/issues/327
where the checkbox icon should be showing. The right aligned text appears correct.

**Comment by wnvko** [comment]
@mddifilippo89 you can reproduce the issue in the storybook samples, just add one more chip:
![image](https://user-images.githubusercontent.com/5990334/163066419-5ddd4f93-60fa-48f1-b1dc-fb624d1ea751.png)
