### ISSUE TITLE
Mixins really necessary??

### ISSUE THREAD

**Issue by gmurray81** [IgniteUI/igniteui-webcomponents#34]
Hey guys, I'm beginning to put together an analyzer that parses these types and will hopefully emit all the boilerplate we need to use this stuff in Blazor, but all the mixin stuff is going to make it more annoying to statically analyze these types. I can probably make it work anyhow. But it doesn't really seem like it was strictly necessary to define that stuff using mixins? Really necessary? Or just "cool" ;-)

**Comment by gmurray81** [comment]
If you do need to keep them, could you at least keep them pretty limited in number?

**Comment by DiyanDimitrov** [comment]
@gmurray81, Currently we have only two mixins - Sizable and EventEmitter. We do not plan adding new ones at least for now.

The reason to use mixins is to implement multiple inheritance since some components has to be sizable, some components should emit events and some components should do both.

If keeping the mixins to a limited number is also an issue, we could possibly remove them by duplicating the size property to all components that support sizing and making the event emitter a base class.

**Comment by gmurray81** [comment]
As long as we don't have a large of different mixins, I can just make the analyzer understand the limited number that we have (sizing/events). Should be ok, I just wasn't sure if you were going to create a ton that would make the behavior difficult to statically analyze. Have you checked whether they interfere with the tooling like the intellisense? I'm guessing the language service is smart enough to figure it out though.

I have a suggestion about the "string enum" type fields with the unioned types that appear on some properties. If those appear in multiple places you might want to create a type alias for them, and that will aid a bit in the analysis, but isn't strictly necessary if the property type is the only place where that union shows up.

**Comment by gmurray81** [comment]
BTW, off-topic, but is dock manager being refactored to use lit-element, or is that continuing to use stencil? Am trying to make this thing understand both, but it would help to know if I should just wait to look at dock manager.

**Comment by DiyanDimitrov** [comment]
> Have you checked whether they interfere with the tooling like the intellisense?

We haven't encountered any issues with the intellisense. The mixins in [lit](https://lit.dev/docs/composition/mixins/) and Typescript in general are a standard pattern so I would not expect any issues. 

> BTW, off-topic, but is dock manager being refactored to use lit-element, or is that continuing to use stencil?

The dock manager will continue to use stencil.
