### ISSUE TITLE
Nav Drawer border with relative position

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-webcomponents#345]
## Description  
The Nav Drawer doesn't include a border when in relative position atm, which can make it a bit hard to visually separate from content if it's also surface colored (which we do a lot to accommodate light/dark themes):
![image](https://user-images.githubusercontent.com/3198469/166672149-d88f74a8-80c3-47cd-8cf9-d33b5610fcfc.png)

It's even weirder in the default Bootstrap light theme where everything lands in the same surface color and even the Nav Bar is lacking any separation at this point so it's all the same:
![image](https://user-images.githubusercontent.com/3198469/166672672-061cbb26-ad1a-4ccc-b0b3-43a8ca922c29.png)

Will still mark this as a question in case there's something wrong with the setup.

## Steps to reproduce  
The attached sample for #344 can be used

## Result  
Since there's no border there's no visual separation from the content

## Expected result  
That's why I'm tagging @sdimchevski  as well, but my expectation would be something similar to this:
![image](https://user-images.githubusercontent.com/3198469/166672317-3c326710-25a7-4400-b792-9bf5183c0eaf.png)

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by sdimchevski** [comment]
We have a right border (grays 300) in the UI kits both in Material and Bootstrap
