### ISSUE TITLE
Icon button colors inconsistencies 

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-webcomponents#352]
## Description  
The icon button colors seem to be quite different between Ignite UI for Web Components and Angular. I realize the latter only has one button, but that should correspond to the `flat` variant still, right? In that case those should be pretty similar, if not identical.

## Steps to reproduce  

1. Run the Icon button story and switch themes
2. Change variant to flat
3. [Optional] Can add the same icon for good comparison:
  ```js
  registerIconFromText(
    'favorite',
    '<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>'
  )
  icons.push('favorite');
  ```
4. Compare with https://www.infragistics.com/products/ignite-ui-angular/angular/components/button#icon-button while switching themes 

## Result
- Material
  - The WC buttons are using `gray-900` while Angular uses `grays-800` which is noticeably lighter
  ![image](https://user-images.githubusercontent.com/3198469/167451387-2910b152-85bb-4498-b35f-3369d377146e.png)
  - There's either no hover state or I can't see it ¯\_(ツ)_/¯
  - The focus state in WC uses a flat circle, which there's some elevation in Angular
- Bootstrap
  - Seems to using primary color in WC where as Angular sticks to the same gray
  - Also completely different hover & focus styling:
  ![image](https://user-images.githubusercontent.com/3198469/167452779-c507c185-3650-444f-8770-37ad6efae6c5.png)
  - The primary color on Bootstrap persists in WC even in the dark theme, which I'm not sure hits contrast targets at all. For example focused Icon button in Bootstrap Dark:
  ![image](https://user-images.githubusercontent.com/3198469/167453457-e1bd6f27-bf75-4fae-a9ed-4ad633c14030.png)
- Fluent
  - foreground color difference from what I see - primary-500 vs the same gray-800
  - Has a similar contrast issue as Bootstrap for dark 
- Indigo 
  - WC using gray this time while Angular is using some variation on primary
  - Hover & focused effects are completely different style 

## Expected result  
Per the description - expecting those to be more similar or the same.
 _Since this is mostly about consistency - some of Angular's implementation might need updating too_

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by desig9stein** [comment]
@damyanpetev are you sure there are inconsistencies with the fluent theme, I can't see any? Both IGX and WC use primary-500, as for the contrast issue  @sdimchevski this change has first to be made in the UI kit, and then we can implement it.

**Comment by damyanpetev** [comment]
@desig9stein I was looking at https://www.infragistics.com/products/ignite-ui-angular/angular/components/button#icon-button since there's an easy theme switcher, but at least there the foreground for fluent is still gray 800
