### ISSUE TITLE
Navigation bar typography different in WC and Angular

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#365]
## Description  
Navigation bar has typography based on `h5` in WC and based on `h6` in Angular

## Steps to reproduce  
Create navigation bar with text as content and compare WC and Angular result.

## Result  
Typography is different in WC and Angular.

## Expected result  
Typography in WC and Angular should be the same

## Attachments  
Web Components navigation bar:
![image](https://user-images.githubusercontent.com/5990334/168067910-0dd0a285-6552-48e7-b365-5abfe4676b64.png)
_Note: typography is applied only to tagged content_

Angular navigation bar:
![image](https://user-images.githubusercontent.com/5990334/168069162-1acf7028-1875-450a-b918-fda1caa4b8d5.png)

**Comment by sdimchevski** [comment]
In the UI kits the title is H6
