### ISSUE TITLE
Badge color is different in Angular and Web Components

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#397]
## Description  
Color of badge is `--primary-500-contrast` in Angular and `--primary-700-contrast` in Web Components

**Comment by SisIvanova** [comment]
@YoannaIvanova can you please check what is the true color of the bootstrap badge in Sketch.

**Comment by YoannaIvanova** [comment]
> @YoannaIvanova can you please check what is the true color of the bootstrap badge in Sketch.

@SisIvanova The badge color is primary.500 in Bootstrap.
