### ISSUE TITLE
Tree Item and Expansion Panel components do not import the Icon component

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-webcomponents#420]
## Description  
The `IgcTreeItemComponent` and `IgcExpansionPanelComponent` use an `IgcIconComponent` internally as an expand/collapse indicator. However, they do not import the icon component in their .ts file.

## Steps to reproduce  

1. See  [Expansion Panel topic](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/expansion-panel)
2. See  [Tree topic](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/tree)

## Result  
The indicators are not rendered in the documentation samples - [Expansion Panel](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/expansion-panel), [Tree](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/tree#web-components-tree-example), except when explicitly defining the `IgcIconComponent`, as in the [Tree LOD sample](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/tree#web-components-tree-load-on-demand). 
This is not the case when running the samples from the igniteui-wc-examples repo locally.

## Expected result  
The IgcIcons to be rendered.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by HUSSAR-mtrela** [comment]
@ddaribo your PR https://github.com/IgniteUI/igniteui-wc-examples/pull/288 did not fix issue with missing icons in Tree samples
https://staging.infragistics.com/webcomponents-demos/samples/grids/tree-basic-example
@mddifilippo89  FYI

**Comment by teodosiah** [comment]
@HUSSAR-mtrela , the issue should be fixed in the components. Defining the Icon component in the samples is a temporary solution until we fix it in the tree component and expansion panel code
