### ISSUE TITLE
IgcTree: should igc-checkbox and igx-circular-progress be registered as side effects

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-webcomponents#423]
## Description  
The `IgcTreeItemComponent` depends internally on `IgcCircularProgressComponent` and `IgcCheckboxComponent`. However, these components are being tree shaked and in case they are not defined explicitly won't be rendered.

So, should our customers define the `IgcCheckboxComponent` and `IgcCircularProgressComponent` on application level or we should register them as side effects so that they are provided out of the box (similar to the `DaysView`, `MonthsView`, `YearsView` and `Icon` components)?

**Comment by rkaraivanov** [comment]
Closed via #426
