### ISSUE TITLE
Proposal: Extract basic input properties into a mixin

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#461]
Wondering if we should mixin all those basic input properties so we don't have to repeat them again and again for other input-based components that can't directly inherit them. Perhaps that'll be just the combo in addition to the select, so might not be such a big deal. Just food for thought.

_Originally posted by @damyanpetev in https://github.com/IgniteUI/igniteui-webcomponents/pull/425#discussion_r928686069_

**Comment by rkaraivanov** [comment]
I'm closing this issue because our existing base classes already cover most of the UI components and behaviors.
