### ISSUE TITLE
Radio group accessibility improvements (MAC only)

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-webcomponents#474]
## Description  
The Mac screen reader tells you which button you are on but not the total number of buttons.
for example, you are on radio button one of one. It should say, you are on radio button one of five...

**Comment by rkaraivanov** [comment]
@desig9stein 

Resurrecting an old issue, but can you test with the current version of the library?

**Comment by simeonoff** [comment]
Seems this issue is only reproducible with VoiceOver in Chrome. Firefox seems to work fine with the current implementation. Safari with VoiceOver can be fixed by adding the radio role to the host of th e `igc-radio` button component.

**Comment by SisIvanova** [comment]
The suggested fix for Safari leads to unwanted double-reading of the radio button label (e.g., "Mango Mango, radio button 2 of 4"), so it won't be implemented for now.
