### ISSUE TITLE
Fluent theme, Rating uses wrong colors

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-webcomponents#481]
## Description  
There are color differences between our fluent theme and [ms fluent](https://developer.microsoft.com/en-us/fluentui#/controls/web/rating#usage)

**Comment by simeonoff** [comment]
@sdimchevski do you plan on updating the designs in the UI kits to reflect the latest changes in Fluent UI?

**Comment by sdimchevski** [comment]
@simeonoff Yep, we've started working on Indigo.Design UI Kit for Fluent in Figma and we plan updating

**Comment by desig9stein** [comment]
@sdimchevski I saw that there are still differences, do you plan to change them or I can safely implement what we have in the kit

**Comment by sdimchevski** [comment]
@desig9stein I don't see notable differences. Only the shape of the star is a little different, colors are more or less the same. We just don't have a hover state which we're gonna include in the next release of the UI kits and it will be primary 800 for Fluent. So yes, you can implement what we have in the Fluent UI kit

**Comment by sdimchevski** [comment]
@desig9stein I see discrepancies between your implementation and what we have in the kit. Please fix the following colors to comply with those in the Fluent UI kit

Light

Full Star:
enabled: warn-900
disabled: warn-100

Empty Star:
disabled: warn-100

Dark

Full Star:
enabled: gray-800
disabled: warn-900

Empty Star:
enabled: gray-400
disabled: warn-900
