### ISSUE TITLE
Calendar prev/next month buttons focus visual state not distinctive enough

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-webcomponents#500]
## Description  
When the previous/next month buttons are focused, the visual state indication doesn't seem to be distinctive enough, specifically in the Bootstrap theme there's barely any difference. Marking this for Bootstrap for that reason, though I believe the Indigo theme might also be too close, depending on requirements for color and contrast value differences to satisfy general accessibility and also color blind users.

## Steps to reproduce  

1. Open the [Calendar Docs](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/scheduling/calendar) or [Stories](https://igniteui.github.io/igniteui-webcomponents/?path=/story/calendar--basic)
2. Focus one of the month buttons (either focus the calendar (date) and shift-tab or click one of the buttons directly)
3. Observe the focused visual state

## Result  
There's a barely perceptible difference in color:
![image](https://user-images.githubusercontent.com/3198469/187677762-9b393bb2-21e8-4b87-9547-de27b795b6af.png)

Close contender with the Indigo theme - same button is focused and it is visible (mostly) but I'm not sure this passes accessibility requirements:
![image](https://user-images.githubusercontent.com/3198469/187678246-8d18fb41-63ab-44e0-8dc7-b52fc57eb3b4.png)

## Expected result  
I'd expect the focused state to be easy to see clearly and follow accessibility standards

**Comment by simeonoff** [comment]
I believe so, yes. We can close it.
