### ISSUE TITLE
Bugs around Accordion documentation & samples

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-webcomponents#520]
## Description  
Go to https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/accordion#api-members

Sample is broken:
![image](https://user-images.githubusercontent.com/14248932/194265794-86e61db7-84c0-4d5a-9653-1bba411dd393.png)

Trying to acces Accordion API docs returnr 404:

https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcaccordioncomponent.html

**Comment by teodosiah** [comment]
It looks like all samples are working properly already:
![image](https://user-images.githubusercontent.com/52423497/206652239-2c9561af-5827-47bc-af2f-d1e2fcb04e14.png)

About the broken links, I've logged it in the [igniteui-xplat-docs](https://github.com/IgniteUI/igniteui-xplat-docs) repo [here](https://github.com/IgniteUI/igniteui-xplat-docs/issues/620).
