### ISSUE TITLE
IgcGrid - cannot set pinned position to end

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-webcomponents#547]
## Description  
cannot set pinned position to end

## Steps to reproduce  
create grid with some pinned columns and attempt to set pinning to the end of the grid
ex: otherGrid.pinning = {columns: ColumnPinningPosition.End};

## Result  
typeError in console: 
TypeError: Cannot read properties of undefined (reading 'End')

## Expected result  
columns are pinned to end of grid

## Attachments  
Attach a sample if available, and screenshots, if applicable.

[CurrTestGrid.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/9993174/CurrTestGrid.zip)

**Comment by damyanpetev** [comment]
Seems like @gmurray81 already fixed this one by exporting the enum (thanks), though as a note the path in the demo might've been a bit old.
Working demo with newer package and updated import path: 
[CurrTestGrid.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/10437618/CurrTestGrid.zip)
