### ISSUE TITLE
IgcGrid - selectRange method

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/igniteui-webcomponents#557]
Looks like selectRange method that makes specified cells selected from code behind is not available in the Web Components grid.

* I confirmed that behavior with Ignite.Blazor 22.2.36

**Comment by damyanpetev** [comment]
The method should be available in the latest WC package of the grids (4.2.5) and work as expected
https://codesandbox.io/s/vibrant-shtern-8tjo70?file=/src/index.ts

The Blazor component is still not fully functional, but that is being tracked internally, so as far as WC are concerned this is done. Closing.
