### ISSUE TITLE
Modal fluent dialog styling

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-webcomponents#603]
## Description  
The modal dialog with the Fluent UI theme is different than the reference implementation.

## Steps to reproduce  

1. Open a dialog with the Fluent theme applied

## Result  
![image](https://user-images.githubusercontent.com/20106115/210764854-936240a9-85cb-419b-9adc-6cea97c163ca.png)

## Expected result  
![image](https://user-images.githubusercontent.com/20106115/210765079-d742c6a4-18ad-4e1e-b707-1bbdc2847cf6.png)

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment]
The issue here is twofold. On the one hand, there was a bug in the dialog theme, which doesn't use the correct CSS variable. On the other hand, the design of the dialog doesn't truly represent the original spec. However, @sdimchevski would need to chip in on this.

**Comment by sdimchevski** [comment]
@simeonoff @rkaraivanov Backdrop's background color in Fluent should be a shade of black, not white. So let's change it to:
background-color: rgba(0, 0, 0, 0.4);
