### ISSUE TITLE
Input helper text inconsistency

### ISSUE THREAD

**Issue by SisIvanova** [IgniteUI/igniteui-webcomponents#619]
## Description  
The input helper text looks different in the components that use input internally. For instance, in the Material theme, the helper text in the combo and the input components has margin-top and padding-inline, but there isn't any padding or margin in the select. The helper text color is also different - gray-600 in the select and the combo components and gray-700 in the input.

Fluent and Indigo themes also have some discrepancies regarding the margins and paddings.

## Attachments  
<img width="1720" alt="Screen Shot 2023-01-16 at 9 09 22 PM" src="https://user-images.githubusercontent.com/59446295/212750938-219e4647-6f68-4bc9-b98a-451d7161e5bd.png">

**Comment by IGSvt** [comment]
The Hint Text (helper text) for the Material theme should have a 16px margin to the left side. For the Idle state the color is grays.700 / Filled state is grays.700 / Disable state is grays.500
