### ISSUE TITLE
Cannot use IgcGridToolbar when a column is present with groupable=true

### ISSUE THREAD

**Issue by agoldenbaum** [IgniteUI/igniteui-webcomponents#628]
**Steps to Reproduce:**
1. Run the attached sample project.

**Behavior:**
IgcGridToolbar is not visible. The group-by area seems to be on top of it.

**Expected Behavior:**
Both IgcGridToolbar and group-by area should be visible.

[toolbar-sample-1.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/10461313/toolbar-sample-1.zip)

**Comment by skrustev** [comment]
@agoldenbaum This seems to be already fixed. Could you try with the latest version
