### ISSUE TITLE
material outlined input has background in disabled state

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-webcomponents#638]
## Description  
The disabled outlined input in the material theme has a background that makes the floating label look cut off, it also forces the user to match his surface/background color to match the disabled background color of the input. This makes the transparent background behind the floating label meaningless.

## Steps to reproduce  

1. Open input
2. switch to a material theme
3. select the outlined version of the input
4. disable the input.

## Result  
<img width="1044" alt="Screenshot 2023-01-27 at 16 34 52" src="https://user-images.githubusercontent.com/21260963/215114378-f3bcbf3f-6304-45ed-86ad-39cf22166273.png">

## Expected result  
<img width="1044" alt="Screenshot 2023-01-27 at 16 46 20" src="https://user-images.githubusercontent.com/21260963/215114557-527caba8-e806-4c68-a58b-da1ccb01981a.png">

**Comment by simeonoff** [comment]
Sorry, I can't reproduce this on the master branch. Are you sure yours isn't stale?

**Comment by desig9stein** [comment]
@sdimchevski @IGSvt is this a mistake in the handoff?

<img width="346" alt="Screenshot 2023-01-27 at 17 14 09" src="https://user-images.githubusercontent.com/21260963/215121188-5eec9e9a-2467-4d11-81ae-73324e40cdf8.png">

I am asking since for me, this makes the whole effort around refactoring the outlined input to have a floating label that has transparent background meaningless.

**Comment by IGSvt** [comment]
The design will be changed, so there is no background for the disabled state.
