### ISSUE TITLE
The Navigation drawer does not display the backdrop when the available space shrinks

### ISSUE THREAD

**Issue by mtsvyatkova** [IgniteUI/igniteui-webcomponents#663]
## Description  
The nav drawer doesn't display the backdrop and doesn't allow to click outside to close it when the initial position is set to 'relative' and the available space shrinks. This differs from the Angular Navigation Drawer (see the image below)

![NavDrawerOverlay](https://user-images.githubusercontent.com/11231206/217874172-d44f6657-1fa8-43c1-9743-b050d163bdd7.png)

**Comment by desig9stein** [comment]
In Angular, there is a threshold with which you can specify when the navdrawer switches from absolute to relative(pinned) position.
In web components, we don't have that option. @simeonoff @SisIvanova again as the [other issue](https://github.com/IgniteUI/igniteui-webcomponents/issues/661) I believe that this is build that way intentionally. If we want to add those functionalities for web components I think those two issues should be feature requests.

**Comment by damyanpetev** [comment]
IIRC, the last time we talked about this it was indeed rejected as a more of an application scenario/pattern (not too unlike the drawer itself tbh). It's not in the spec, thus it would be a feature request indeed. Though not just for the component - even on a design system level and not just for me to decide. There are already internal issues and discussions refencing this btw and I don't mind bringing it up on the next sync.
