### ISSUE TITLE
icon-button wrong size in flex container

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#669]
## Description  
When `icon-button` is added to flex container it occupies container's entire height.

## Steps to reproduce  
Add `icon-button` in flex container with some big height. Inspect the height of the `icon-button`.

## Result  
`icon-button` occupies the entire height of its flex container.

## Expected result  
`icon-button` height should not be affected by its parent container.

## Attachments  
![image](https://user-images.githubusercontent.com/5990334/219338734-a634de58-cb99-4267-9ba4-83d877a83a21.png)

**Comment by igdmdimitrov** [comment]
Same issue with the `igc-avatar`
