### ISSUE TITLE
Review access modifiers to ensure proper Blazor API generation

### ISSUE THREAD

**Issue by gmurray81** [IgniteUI/igniteui-webcomponents#67]
## Description  
Could someone review the methods/properties that are currently public on the components and shift any to protected/private that don't need to be exposed? I'm seeing some inconsistencies where a method like renderContent might be protected on one component  and public on another. It's important that anything that isn't intended to be public be hidden or we will automatically expose it up on the Blazor API also.

**Comment by gmurray81** [comment]
note, in a PR I've added a `@blazorSuppress` decorator that can be used to suppress a member that we would not like to appear on the blazor API, but should be considered accessible at that TS level. But in most cases if a method is accessible at the TS level we would want it accessible at the Blazor level, I assume. So its best just to make sure that each member has the appropriate visibility.

**Comment by gedinakova** [comment]
This is great, Graham, we may need the @blazorSuppress decorator for some props like the static `styles` one.
