### ISSUE TITLE
[IgcGrid] - IgcToolbar doesn't render when there is grouping

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-webcomponents#688]
## Description  
Toolbar doesn't render when there is grouping

## Steps to reproduce  

run sample attached

## Result  
the toolbar doesn't render
## Expected result  
the toolbar renders

## Attachments  
[column-hiding-toolbar.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/10885213/column-hiding-toolbar.zip)

**Comment by damyanpetev** [comment]
Duplicate of https://github.com/IgniteUI/igniteui-webcomponents/issues/628, that's already fixed and should be out with the next package updates
