### ISSUE TITLE
npm run build:publish can't run on windows shell

### ISSUE THREAD

**Issue by gmurray81** [IgniteUI/igniteui-webcomponents#690]
## Description  
run npm build:publish on windows shell (non-bash) and an error is produced from clean:styles

## Steps to reproduce  

see description

## Result  
Error: Command failed: npm run clean
Error: Illegal characters in path.

this is caused by the rimraf syntax being used in the clean:styles script being bash dependent.

## Expected result  
script should run on windows also.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by rkaraivanov** [comment]
Hmm, this should be resolved as it occurred in #635 and was resolved by reverting it in #648
Can you do a clean install from package-lock and try again?

**Comment by gmurray81** [comment]
yep, my bad, I hadn't npm installed after pulliing.
