### ISSUE TITLE
Cannot remove IgcGrid group expressions if they were added programmatically

### ISSUE THREAD

**Issue by agoldenbaum** [IgniteUI/igniteui-webcomponents#700]
Tested against latest dev build at the time of writing this. (22.2.0-dev.1178)

1. Run the attached sample project. You may need to do an npm install --legacy-peer-deps due to webpack configs.

Actual Behavior:
- Cannot remove the group-by descriptions from the group-by area

Expected Behavior:
- Should be able to remove the group-by descriptions from the group-by area

[groupby-expressions.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/10960113/groupby-expressions.zip)

**Comment by mddifilippo89** [comment]
@dkamburov is this being worked on this month?
