### ISSUE TITLE
Stepper Styling (material) differs from Angular Stepper (and Figma) - Potential issue

### ISSUE THREAD

**Issue by andiesm813** [IgniteUI/igniteui-webcomponents#704]
## Description  
If you see the current [Stepper Sample in Storybook](https://igniteui.github.io/igniteui-webcomponents/?path=/docs/stepper--basic&globals=theme:material), when you advance on the steps, the previous ones don't get the "completed" style, like the Angular sample has (and also the Figma UI kit version too).

![image](https://user-images.githubusercontent.com/86068582/225379285-140714ba-82e7-4a8a-997b-e1609f3d3442.png)

I'm saying this is a potential issue because maybe the "completed" style is already implemented, but the sample is not 100% functional and the steps never change their look to the completed style. 

## Expected Result
1. Steps 1 and 2, who are supposed to be completed (if step 3 is the active one) should change their color to that dark gray and white foreground.
2. The progress line also turns darker.
3. The steps ahead (not completed) also have like a "disabled" style.

**Comment by ddaribo** [comment]
Hi @andiesm813,

The `completed` property of the `IgxStepComponent` and the corresponding `complete` of the `IgcStepComponent` are intended to be controlled by the developer.

The Angular [demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/stepper#angular-stepper-example) from the screenshot has its steps’ completed property bound to custom conditions in the template, for instance:
`<igx-step #step2 [isValid]="businessInformationForm.form.valid" [completed]="businessInformationForm.form.valid">`

The `IgcStepper` storybook does not contain such logic. It can be added, for example setting the `complete` property of the previosuly active step to `true` on user interaction when the `igcActiveStepChanging` event is emitted:
`<igc-stepper .. @igcActiveStepChanging=${handleActiveStepChanging} >`
```
  const handleActiveStepChanging = (ev: CustomEvent<any>) => {
    const oldActiveStepIndex = ev.detail.oldIndex;
    const stepper = document.getElementById('stepper') as IgcStepperComponent;
    stepper.steps[oldActiveStepIndex].complete = true;
  }
```

In this line of thought, it appears the [Web Components Stepper Example](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/stepper#web-components-stepper-example) does not mark the steps as completed and in that sense differs from the Angular demo. Maybe that should be addressed for the sample, @teodosiah?

**Comment by teodosiah** [comment]
Sure, @ddaribo, can you please log it into the Web Components samples repo?

**Comment by ddaribo** [comment]
[Logged](https://github.com/IgniteUI/igniteui-wc-examples/issues/387).
