### ISSUE TITLE
Need a null check in the sample

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-webcomponents#708]
Sample from WC sample browser throwing attached error :
/webcomponents-demos/samples/grids/grid/row-drag-base

There needs to be a null check in the onGridRowDragEnd code. For example:  
Textpublic onGridRowDragEnd(args: any): void {        
        const ghostElement = args.detail.dragDirective.ghostElement;
        if (ghostElement == null)
        {
            console.log("null ghost elemenrt");
            return;
        }

error:
![image](https://user-images.githubusercontent.com/22081100/226718955-849080a2-4d6c-4fca-b5d9-3df0ea64a016.png)
![error1](https://user-images.githubusercontent.com/22081100/226719081-07726830-d0de-42f7-a40a-652c962b4e8b.png)

**Comment by rkaraivanov** [comment]
Playing with the current version of the demo samples, it seems to have been fixed.
