### ISSUE TITLE
An igc-tabs inside an igc-tab-panel (nested tab components) doesn't work well

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-webcomponents#713]
## Description  

An `<igc-tabs>` inside an `<igc-tab-panel>` (nested tab components) doesn't work well.

## Steps to reproduce  

1. Put `<igc-tabs>` component inside another `<igc-tabs>` and its `<igc-tab-panel>` component, like the following code.

```html
<igc-tabs>
    <igc-tab panel="home">
        Home
    </igc-tab>
    ...
    <igc-tab-panel id="home">

        <igc-tabs>
          <igc-tab panel="P1">P1</igc-tab>
          ...
          <igc-tab-panel id="P1">
              Panel 1
          </igc-tab-panel>
          ...
        </igc-tabs>

    </igc-tab-panel>
    ...
```

3. Run it and click the tab in  the tab panel.

## Result  

The child tab contents disappeared.

![movie-002](https://user-images.githubusercontent.com/102948935/227433685-6279412b-27c7-4186-9d22-0cef2f4b39b4.gif)

## Expected result  

An active tab and its contents should be switched correctly.

## Attachments  

You can reproduce this issue with the project attached below. (After downloading and extracting it, executing `npm i` and `npm start` will launch the app.)

[📦nested-igc-tabs.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/11058857/nested-igc-tabs.zip)

**Comment by damyanpetev** [comment]
Reopening as this seems to reproduce again
