### ISSUE TITLE
Hint is visible when select is open

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#723]
## Description  
When `open` is set to `true` in the select, and select has a hint the dropdown is shown under the hint

## Steps to reproduce  

1. Create select with hint and set its `open` to `true`.

## Result  
Dropdown is shown under the hint.

## Expected result  
When dorpdown is open hint should not be visible

## Attachments  
![image](https://user-images.githubusercontent.com/5990334/229719628-1ab37844-3ffe-4727-91af-b1eb8b1f7ebf.png)

**Comment by ddaribo** [comment]
There is a similar displacement for the `IgcDropdown` as well when the `open` property is set in the template initially. Sample [here](https://codesandbox.io/s/igx-dropdown-initial-open-63eo4o).
