### ISSUE TITLE
Request: please add properties rather that controlling something only via a style with an attribute selector.

### ISSUE THREAD

**Issue by gmurray81** [IgniteUI/igniteui-webcomponents#74]
## Description  
For scenarios like `size` on `IgcInputComponent` there is no property that exists to inform the Blazor API gen that there is a settable attribute with a given name that will have some effect given the css. If a property were to exist (even it if didn't do anything logic-wise) it would be better for documentation purposes, and would allow the auto-generation of the wrapping APIs to be automatic. Could we make sure to have a descriptive property in these kinds of cases?

**Comment by gmurray81** [comment]
if for some reason its not desirable to have properties to do this (although I think it would probably help from an API documentation and intellisense standpoint) then perhaps we could have some decorator that will inform the API generation that additional settable attributes exist that will achieve some effects.

**Comment by rkaraivanov** [comment]
@gmurray81 
Care to elaborate on "no property that exists to inform the Blazor API"? All the "sizable" components extend the sizable mixin class which does expose a property.
https://github.com/IgniteUI/igniteui-webcomponents/blob/f3cd9b3c85ea40134df54102560d09773ba12cf3/src/components/common/mixins/sizable.ts#L12-L18

**Comment by gmurray81** [comment]
@rkaraivanov whoops! That's my error, I missed that there was a property up there that needed to be pulled in. The auto-generation wasn't spidering up to it. I thought maybe only the css was taking queues off attributes being set. Great, I can work with that.
