### ISSUE TITLE
Question: Why no event args?

### ISSUE THREAD

**Issue by gmurray81** [IgniteUI/igniteui-webcomponents#75]
## Description  
I'm wondering why none of the custom events being raised have any arguments?
I need to be able to do things like backpropagate a value up to the Blazor API, so it would be useful if events like IgcInput and IgcChange included the current value in the arguments. I could probably invent some stuff to make this work if need be without the arguments being provided, but I was wondering why these are all essentially void?

**Comment by gmurray81** [comment]
In some ways, in terms of the blazor support, it would actually be simplest if there were specifically a custom event that fired that is the changed value as the argument, with no extra wrapping etc.

We do actually have engine pieces for carrying complex event args back out that we use for the DV stuff, but I'm considering allowing for a simpler setup for most of these components than running our full engine since the full engine is probably overkill for things like input or button, but if I'm using a simpler strategy, I may not be able to use the full event args support.

**Comment by rkaraivanov** [comment]
@gmurray81 
We've decided to go with the default behavior of form controls in the browser and the usual handling of these events.
That is, accessing the value through event -> target -> value in your callback.

We might possibly need to expose additional arguments in the custom events for some behaviors/states but for the current set of implemented controls we didn't have to.

**Comment by gmurray81** [comment]
Ok... hmm... if you are going to keep it that way, I suspect I may need to do something tricky to augment the event on the way out of JS land. 

The challenge here is that with Blazor the communication between the .net code and the DOM is over an asynchronous bridge. When an event is fired, we can't synchronously respond to it and some time might pass before the .net handler fires.

For things like change/input we'd want to update the Value property up in .NET at the same time as those events fire, but if the new value isn't on the arguments, we'll have to make a separate asynchronous communication to get the current value from the DOM. This will make the potential for things getting out of sync even more pronounced than it starts with in Blazor.

I think the easiest solution would be if the args about a value changing contained the actual value, then we can use all our existing mechanisms to keep things in sync up at the blazor level. But if you guys wont do that, I'll may have to try to jump through some interesting hoops to gather extra info from the target in some glue logic i put together down in JS land or something.

BTW, this forced asynchronousness in Blazor means that it would be best if you don`t rely on the users mutating the event arguments to achieve some sort of effect, or mutating the component DURING the handler. That kind of timing wont be possible in Blazor, because of the async communication between the .NET logic and the JS logic. In these scenarios we at least need another way to operate for Blazor. In the worst case, we are operating on `Blazor Server` mode where the .net logic is actually running on the server, rather than in webassembly in the same browser tab, and there could be real delays in when the event fires and when the handler logic is run in .net.

**Comment by rkaraivanov** [comment]
In that case we should probably expose the values as event arguments just for the sake of skipping the potential implementation
hoops for Blazor land. Developers can ignore them in "pure" DOM environment and go with the usual route while other frameworks won't try to work around it. I'll bring this in discussion with @DiyanDimitrov and @damyanpetev

As for the your second point, we don't plan to expose reflecting/modifying component state through mutating event arguments. 
If the developer wants to modify component props in the handler, he can get a reference to the component or use the mechanism of their favorite state management library.

**Comment by gmurray81** [comment]
@rkaraivanov sounds good. Yeah, if you didn't add the values I could find some way to work around, but I think adding the values to the args is better. 

But on the second point, if the API is designed in such a way to rely on synchronous communication from the event handlers, that provides a big barrier for Blazor. Even things like stopPropagation and preventDefault are pretty tricky. You need to anounce them up front when attaching a handler or its a no go, due to the lack of async.

Our one fallback is that we generally also allow for a JS based event handler to be attached. But its just better if we avoid these kinds of patterns in the API design if possible.

**Comment by rkaraivanov** [comment]
I'm closing this issue. If additional work is required we can open a new one where the discussion can take place.
