### ISSUE TITLE
IgcDataGrid - part of grid will disapper by tab key

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/igniteui-webcomponents#757]
## Description  
This is the strange behavior of IgcDataGrid (it means old version of grid). 

## Steps to reproduce  

1. Open this sample https://www.infragistics.com/webcomponents-demos/samples/grids/data-grid/cell-editing
2. Show a few of rows by using filter.
3. Chage the window size in order to show horizontal scroll bar.
4. move focus by tab key.
5. Sometimes, grid will have white blank.
6. If move scroll bar, white blank will be gone.
*In my guess, it will happen if using template culumn and with horizontal scroll bar.

## Result  
Sometimes, grid will have white blank.

## Expected result  
Grid can be shown anytime.

## Attachments  
![4012ba9faee16c27656c3910a56c88da (1)](https://user-images.githubusercontent.com/5829221/235556536-f75c4fde-5a4c-42df-bb06-c0239c673b7b.gif)

**Comment by kdinev** [comment]
@cleverdog Technically the `IgcDataGrid` is a deprecated component, but including @gmurray81 f there's a quick solution that can be provided. In general, we won't be maintaining this component and would like users to move to `igc-grid` instead.

**Comment by gmurray81** [comment]
@ig-robstoffers I suspect what is happening here is that likely the page adjusted the scrollLeft position in such a way that the scroller did not notice, perhaps, which likely didn't trigger the visibility check. I think I've seen this before in firefox where in some cases it will restore the scroll state on a refresh in such a way that we aren't notified. There is probably just some additional situation that needs to be listened for.

**Comment by gmurray81** [comment]
@cleverdog , at a guess, I assume that if you start manipulating the scrollbar the blank area vanishes?

**Comment by ig-robstoffers** [comment]
@gmurray81 The issue is actually the template cells with buttons that get hidden after the filter. The buttons are obtaining focus when they really should not be in this scenario. My tentative fix for this was to loop through template cells and for any focusable elements that exist I would set the `tabindex` to "-1" when they are hidden and then reset the index (if needed) when the cell is brought back into view.

**Comment by ig-robstoffers** [comment]
@cleverdog After some internal discussion we have come to the conclusion that for template content such as the one in the sample, it is recommended that any focusable elements like `<button>` or `<input>` should have their `tabindex` attribute set to -1 so they are prevented from receiving tab focus.  If a user needs their custom template content to obtain focus they can manually focus the elements when the template cell becomes active. The `activeCellChanged` event will help detect when the cell is active at which point the user can focus their custom content as desired.

There is, however, a similar issue that occurs even if you make the template content unable to gain tab focus. The data grid's own editor cell can erroneously obtain tab focus in some circumstances. I am currently trying to address this issue.

**Comment by cleverdog** [comment]
@ig-robstoffers Thank you for the investigation. I got it, I will continue to watch here.

**Comment by cleverdog** [comment]
I confirmed this issue has resolved in current version, thank you.
