### ISSUE TITLE
IgcGrid + IgcCombo integration scenario issues

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-webcomponents#781]
## Description  
When combo is templated inside the igcGrid cell's there are some issues that arise from the combo list items rendering inside the grid, main ones being:
-  Combo's list items get cut-off (cannot go outside the grid's display container since it does not show overflows):
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/10397980/19c036a7-c984-4a29-acac-7586d82dd91a)
- Grid's Resize observer gets triggered a lot both on initial rendering and on any combo interaction:
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/10397980/3e717df1-d9d6-4110-993e-f318204c8d32)

Need some way to render and position list items outside of the grid (maybe in overlay like in angular's combo).

## Steps to reproduce  

1. Run sample: 
[combos.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/11662516/combos.zip)

## Result  
Issues with combo content getting cut-off and resize observer triggering on any combo render and interaction.

## Expected result  
Combo rendering with no cut-off and not triggering resize observer so much. Preferably working like in the [angular combo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cascading-combos#angular-grid-with-cascading-combos-sample-overview) when integrated inside the grid. 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment]
> Grid's Resize observer gets triggered a lot both on initial rendering and on any combo interaction

That seems to be a issue with the grid observer itself :) I mean, there should be nothing the Combo can do to break that. Honestly, I'm thinking there's a bigger issue there as it also triggers quite a lot on certain Angular/WC samples without Combos being involved and just about all of our tests.

**Comment by rkaraivanov** [comment]
> #698 probably related to first issue too. Again, dropdown related component rendered inside another component.

In this scenario you can try setting `position-strategy="fixed"` and it will probably break out of the clipping context of the ancestor. Not 100% guarantee to resolve the issue in the grid, though.

**Comment by MayaKirova** [comment]
> > Grid's Resize observer gets triggered a lot both on initial rendering and on any combo interaction
> 
> That seems to be a issue with the grid observer itself :) I mean, there should be nothing the Combo can do to break that. Honestly, I'm thinking there's a bigger issue there as it also triggers quite a lot on certain Angular/WC samples without Combos being involved and just about all of our tests.

I was able to reproduce it in angular as well so it is now logged here: https://github.com/IgniteUI/igniteui-angular/issues/13091

**Comment by MayaKirova** [comment]
> > #698 probably related to first issue too. Again, dropdown related component rendered inside another component.
> 
> In this scenario you can try setting `position-strategy="fixed"` and it will probably break out of the clipping context of the ancestor. Not 100% guarantee to resolve the issue in the grid, though.

Unfortunately it didn't:
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/10397980/ee825042-c00c-4882-baee-e5d00aa276da)
