### ISSUE TITLE
CellType has no row property

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#787]
## Description  
I am trying to create a cell template in the grid. In the template I need to take the value of cell related row data. To do so I am trying something like this:
```
public idCellTemplate = (ctx: IgcCellTemplateContext) => html`
	<p>
		${ctx.cell.row.data['FIELD_NAME']}
	</p>
`
```

However, the `cell` has no `row` property.
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/5990334/4102dcae-399e-429b-9847-c044cbd5a485)

**Comment by damyanpetev** [comment]
Property should be available in the next version(s). Until that point, type asserting the context or cell `as any` is a possible workaround, since the underlying js property should be there runtime.
