### ISSUE TITLE
Select - deprecate for removal same-width and position-strategy

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-webcomponents#789]
Migrate the `<igc-select>` properties to match the `<igc-combo>` behavior.
```typescript
{
 protected positionStrategy = 'fixed'
 protected sameWidth = true;
}
```

**Comment by damyanpetev** [comment]
@rkaraivanov @simeonoff Thoughts if we should also replicate the combo flip default?
https://github.com/IgniteUI/igniteui-webcomponents/blob/a1214922e75000045b3eefc722be70e943ff469a/src/components/combo/combo.ts#L235-L237

Can move to a separate issue, but seems related enough even for this one.

**Comment by simeonoff** [comment]
> @rkaraivanov @simeonoff Thoughts if we should also replicate the combo flip default?
> 
> https://github.com/IgniteUI/igniteui-webcomponents/blob/a1214922e75000045b3eefc722be70e943ff469a/src/components/combo/combo.ts#L235-L237
> 
> Can move to a separate issue, but seems related enough even for this one.

You mean deprecate?

**Comment by damyanpetev** [comment]
@simeonoff @rkaraivanov I meant exactly that - replicate/copy the combo. Just now noticed the select does inherit all the things and technically has it exposed already. Not too discoverable through docs/wiki. If hiding it constitutes a deprecation - I'm okay with it if you are.

PS: Honestly, not sure slapping hidden flags on inherited API is a thing we should maintain - doesn't really work the way we'd like; I mean I can still see `same-width` on the Select in the `custom-elements.json` and similarly it'd pop up for intellisense too :C
