### ISSUE TITLE
Date Time Input: '24' shown instead of '0' for hours for "HH" displayFormat in Chrome

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-webcomponents#803]
## Description  
Seems to be reproduced for locales having their `hour12` option as `true` by default.

## Steps to reproduce  

1. Open [this sample](https://codesandbox.io/s/date-time-input-hour-cycle-t4t5vd?file=/src/index.ts) in Chrome and in Mozilla Firefox.
2. Paste " 22/06/2023 00:05" in both inputs.

## Result  
In Chrome, the input having "en" locale, displays "24" instead of "00" once blurred. The other, having "bg-BG" locale, displays "00".
In Mozilla, both inputs display "00".

## Expected result  
As in Mozilla.

## Attachments  
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/35433937/99fe53c3-7860-44d8-afb4-d37f68b1d3db)

**Comment by rkaraivanov** [comment]
@ddaribo @onlyexeption

Related to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1045791) and an ambiguous definition in the ECMAScript specification.

@onlyexeption
Remove the `hour12` parameter of the Intl format options in the date utilities and use the `hourCycle` parameter where:

| Mask flags | `hourCycle` value |
| ---------- | --------------- |
| h/hh       | h12             |
| H/HH       | h23             |
