### ISSUE TITLE
Combo converts value keys to string

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#810]
## Description  
I am using a combo as an editor in the grid. Here is how I do this:
```js
  public comboInlineEditorTemplate = (ctx: IgcCellTemplateContext) => html`
    <igc-combo .data="${this.friends}" .value="${ctx.cell.editValue}" @igcChange="${(e: CustomEvent<IgcComboChangeEventArgs>) => ctx.cell.editValue = e.detail.newValue}"
        value-key="id"
        display-key="first_name"
        master_view-scope
        class="combo">
    </igc-combo>
  `

My data has this structure:

```ts
export interface Friend {
	id: number;
	first_name: string;
	last_name: string;
}
```

What happens is when combo get the value from the grid cell it is an array of numbers. When `igxChange` fires `e.detail.newValue` returns an array of string. This effectively breaks the selection in the combo as well as the editing in the grid.

**Comment by dafo** [comment]
This issue can be still reproduced in "igniteui-webcomponents": "~4.3.0".
It can be tested in this sample - https://github.com/wnvko/templates/tree/master/web-components

**Comment by simeonoff** [comment]
> This issue can be still reproduced in "igniteui-webcomponents": "~4.3.0". It can be tested in this sample - https://github.com/wnvko/templates/tree/master/web-components

I'm having difficulties installing the licensed packages even though I have configured .npmrc with the required credentials with which I can login in the browser. Hence, it's difficult for me to test your sample. If it can be reproduced in a stackblitz sample, that would be great.

**Comment by rkaraivanov** [comment]
@dafo 
Looking at [this snippet of code](https://github.com/wnvko/templates/blob/55fa19006f8cc93f831d68e0bf3cfe812d0bfef6/web-components/src/app/master-view/master-view.ts#L60-L65), you are trying to access the `newValue` when there is a **valueKey** property set which returns the respective key from the selection.

The combo event is defined as:
```typescript
export interface IgcComboChangeEventArgs<T extends object = any> {
  newValue: Array<T | T[keyof T];
  items: T[];
  type: ComboChangeType;
}
```
which means if you have a value key set (i.e `keyof T`) the combo will always return the resolved value of the value key.

If you want the actual data records you need to either access the **items** property in the event or skip
defining a **valueKey**.

**Comment by wnvko** [comment]
Here is a SandBox sample. Just open the combo and try to select some items.
https://codesandbox.io/s/fervent-montalcini-mt2ffq?file=/src/index.ts

**Comment by wnvko** [comment]
@rkaraivanov and @simeonoff
What we are trying to achieve is updating stright away the grid's cell value. What we need is something like this:
```
@igcChange=[event] => [cellValue] = [event].[someEventPramether]
```
I know we can add some logic and solve this. However, my expectation is if the combo value is some type, e.g. array of numbers, change event should provide same type in `details.newValue`.

**Comment by wnvko** [comment]
> @wnvko this is not related to the combo. This is actually an issue with the change detection of the igcGrid. maybe the same as #736. If you double click inside a cell, containing combo - selection is working as expected.

The sample I posted above is a stand alone combo. It is an issue in the combo IMO.
