### ISSUE TITLE
Combo: The floated label jumps up and down on focus

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#818]
## Description  
The floated label jumps up and down on focus in the multi-select combo material box and outlined variants when no value is selected and no placeholder is present

## Expected result  
The label should not float on focus when no selection is made and no placeholder is present.

## Attachments  
https://github.com/IgniteUI/igniteui-webcomponents/assets/4118303/0ffe7aa8-a16d-4378-b469-a1e9ef98a974

**Comment by damyanpetev** [comment]
Besides jumping, it returns to it's 'placeholder' position, which is not intended for outlined inputs, right?
https://igniteui.github.io/igniteui-webcomponents/?path=/story/combo--basic&args=outlined:!true;placeholder:&globals=theme:material - clear value and open
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/3198469/5e23df6e-c63e-4b2c-a651-14787a3bb445)
I think it's the same issue, but let me know if it should be logged separately

**Comment by desig9stein** [comment]
> Besides jumping, it returns to it's 'placeholder' position, which is not intended for outlined inputs, right? https://igniteui.github.io/igniteui-webcomponents/?path=/story/combo--basic&args=outlined:!true;placeholder:&globals=theme:material - clear value and open ![image](https://user-images.githubusercontent.com/3198469/253222665-5e23df6e-c63e-4b2c-a651-14787a3bb445.png) I think it's the same issue, but let me know if it should be logged separately

@damyanpetev I was the same problem, it is fixed now
