### ISSUE TITLE
Multi Column Combo Box doesn't display properly in MatDialog when scrolled down on page

### ISSUE THREAD

**Issue by nathanbloom2015** [IgniteUI/igniteui-webcomponents#860]
## Description  
When using a multi column combo box inside of a MatDialog, the list doesn't display in the correct position if the user is not scrolled to the top of the page.

## Steps to reproduce  

1. Create a multi column combo box with some dummy data inside of a MatDialog
2. Create a button to prompt the MatDialog to open. Put a bunch of <br> tags before the button so the user has to scroll down to click it
3. Run the application, open the dialog window, and attempt to use the combo box
## Result  
The list is either not appearing or appearing in the incorrect spot, depending on how far down on the page the user is scrolled

## Expected result  
The list should appear directly underneath the combo box like it usually does

## Attachments  
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/12667493/fd72aee5-07e1-49cc-864c-3c3d1006ecd5)

**Comment by simeonoff** [comment]
@nathanbloom2015 Can you provide a stackblitz sample reproducing the problem?
