### ISSUE TITLE
IgcDialog - how to tell whether okay or cancel is clicked?

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-webcomponents#941]
IgcDialog - how to tell whether okay or cancel is clicked?

**Comment by rkaraivanov** [comment]
Can you provide a more specific scenario?

I assume this has to do with slotted buttons similar to the sample below.
[![Edit sweet-ishizaka-d9zght](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-ishizaka-d9zght?fontsize=14&hidenavigation=1&theme=dark) 

If that is the case, then it's up to the developer to wire up any additional logic for their slotted controls.
