### ISSUE TITLE
IgcDataGrid - error message will move to out of grid

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/igniteui-webcomponents#950]
## Description  
The error message will move to out of grid by certain operations.

## Steps to reproduce  

1. Open [this sample](https://www.infragistics.com/webcomponents-demos/grids/data-grid/cell-editing). checked with v4.3.0
2. Show error message by edit some cell with blank.
3. Click other cells.

## Result  
 The Error message is moving to out of grid.
![7f5eadb2ab8d822da529a5c32c4b7e32](https://github.com/IgniteUI/igniteui-webcomponents/assets/5829221/a7aa21e9-0bba-4d52-a90b-7120aef36c27)

## Expected result  
It stays in place

**This issue did not occur in previous versions. Here is a [sample](https://codesandbox.io/s/wispy-frost-skzr8q?file=/src/index.ts) for v3.2.2.**

**Comment by ChronosSF** [comment]
@gmurray81 , not sure we still support this as it's deprecated but I am assigning it to you in either case.

**Comment by cleverdog** [comment]
I confirmed this issue is solved with v4.6.0, thank you!
