### ISSUE TITLE
IgcDataGrid - Text is lost when inputting Japanese.

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/igniteui-webcomponents#951]
## Description  
Text is lost when inputting Japanese during certain operations.

## Steps to reproduce  

1. Open [this sample](https://www.infragistics.com/webcomponents-demos/grids/data-grid/overview). checked with v4.3.0
2. Change input mode to Japanse.
3. Start to edit any cell.
4. Press "A" key to input Japanse "あ", then press enter key to fix the input text.
5. Repeat No.4 several times.
6. Finaly, press enter key to comple the cell editing.

## Result  
Only the last input text is reflected in the cell.
![b364aadbd7e8e31fcc23ab593dc1c0aa](https://github.com/IgniteUI/igniteui-webcomponents/assets/5829221/fce43db4-cb26-4abc-9bb1-66655df9ba64)

## Expected result  
Inputs fixed in the middle will be reflected as well.

This issue did not occur in previous versions. Here is a [sample](https://codesandbox.io/s/cranky-benz-8fkdgy?file=/src/index.ts:3208-3942) for v3.2.2.

**Comment by ChronosSF** [comment]
@gmurray81 , same case as the other igcDataGrid.

**Comment by gmurray81** [comment]
This is probably already resolved

**Comment by cleverdog** [comment]
I guess this fix has not included current 4.3.2, can we expect including at next timing?

**Comment by ig-robstoffers** [comment]
I believe I had fixed this back around the end of last month and I couldn't reproduce the issue in my local sample... but I did reproduce it in your codesandbox after updating to the latest packages. I'm assuming that the codesandbox did actually update to the latest package version so I am currently trying to figure out why the fix is not there.

**Comment by ig-robstoffers** [comment]
It appears that the fix was simply not included in that 4.3.2 build. I tested later internal builds and the code changes were present and the issue resolved. So I'm confident you will see this issue resolved in our next update.

**Comment by cleverdog** [comment]
I confirmed this issue is solved with v4.6.0, thank you!
