### ISSUE TITLE
IgcTreeGrid - resizing the width from scrolled to the right caused errors and the order of the columns was broken

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-webcomponents#952]
## Description  

Resizing the width of the IgcTreeGrid from scrolling to the right caused errors, and the order of the columns was broken.

## Steps to reproduce  

1. Shrink the width of the IgcTreeGrid.
2. Scroll to the right of the scrolling area of the IgcTreeGrid.
3. Widen the width of the IgcTreeGrid. 

## Result  
Some errors were reported in the browser's dev console. And the order of the columns was broken.

## Expected result  
Nothing should happen.

## Attachments  

See also the video below.

https://github.com/IgniteUI/igniteui-webcomponents/assets/102948935/f5e54aba-52bf-43f0-923f-2994afed1847

The project that can reproduce this issue is below.

[📦c-00233104-html-app1.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/12891226/c-00233104-html-app1.zip)

**Comment by mddifilippo89** [comment]
Still occurring latest internal WC. See attached sample using @infragistics/build 23.2.90

![image](https://g
[overview.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/13652929/overview.zip)
ithub.com/IgniteUI/igniteui-webcomponents/assets/17785923/56352433-df92-42a7-bf9f-5a70d5a3d0e9)

**Comment by kdinev** [comment]
@damyanpetev Which branch are the igc-grids produced from?

**Comment by dkamburov** [comment]
> @damyanpetev Which branch are the igc-grids produced from?

`blazor-angular-elements`

**Comment by damyanpetev** [comment]
The branch is quite a bit behind and syncing in full can have some unforeseen effects and require more revalidation - still agree it needs to be done as soon as possible, but for this fix specifically being very small I can cherry pick it directly.

**Comment by damyanpetev** [comment]
Done. Next internal build should have this fix in

**Comment by kdinev** [comment]
@damyanpetev Let's plan merging the elements branch at the beginning of 2024. Preferably in January.

**Comment by damyanpetev** [comment]
Yes, please :)

**Comment by MayaKirova** [comment]
Seems to be fixed in version 5.0.0.
