### ISSUE TITLE
IgcPivotGrid - In a pivot data selector, selecting a value item or a column item after deselecting all caused errors.

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-webcomponents#953]
## Description  
In an `igc-pivot-data-selector` with an `igc-pivot-grid`, selecting a value item or a column item after deselecting all items caused errors.

## Steps to reproduce  

1. Build an application with an `igc-pivot-grid` and an `igc-pivot-data-selector`. Make a row item, a few column items, and a value item selected by default.
2. Run it.
3. Unselect all items in the `igc-pivot-data-selector`.
4. Select the value item.

## Result  
Runtime errors will be reported in the web browser's console. One of the error message is below.

```
combined.js:6164  ERROR TypeError: Cannot read properties of undefined (reading 'dimensionValues')
    at t2.extractFromDimension (combined.js:46164:39)
    at t2.extractFromDimensions (combined.js:46160:20)
    at t2.ngOnChanges (combined.js:46141:82)
    at t2.ak (combined.js:4512:29)
    at F3 (combined.js:4800:8)
    at Vk (combined.js:4807:93)
    at $E (combined.js:4794:67)
    at M0 (combined.js:4781:25)
    at nT (combined.js:6780:23)
    at oT (combined.js:6834:5)
```

## Expected result  
Selecting a value item should work fine.

## Note
Selecting a row item after deselection all items worked correctly.

## Videos

https://github.com/IgniteUI/igniteui-webcomponents/assets/102948935/1f2865c7-dbb0-4100-845b-8f31f7422a36

https://github.com/IgniteUI/igniteui-webcomponents/assets/102948935/d44e9194-721a-4d61-a859-43e1877d02e9

### Sample code

[📦c-00232834-igc-pivot-grid.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/12912169/c-00232834-igc-pivot-grid.zip)

**Comment by jsakamotoIGJP** [comment]
@kdinev I've rechecked this issue on the latest version of the "Ignite UI for WebComponents", v.4.7.1.

[📦c-00232834-igc-pivot-grid (v.4.7.1).zip](https://github.com/IgniteUI/igniteui-webcomponents/files/14176425/c-00232834-igc-pivot-grid.v.4.7.1.zip)

As a result, I've seen the error was still there. I understand that this result is due to the fixed version not yet being released as an npm package. Is that my understanding correct?

**Comment by dkamburov** [comment]
@jsakamotoIGJP We'll need to introduce the fix for the igc-pivot-grid as well, you can expect the fix in the next official release of Ignite UI for WebComponents

**Comment by jsakamotoIGJP** [comment]
@dkamburov I understand. Thank you for your reply!
