### ISSUE TITLE
IgcGrid - resizing the width from scrolled to the right caused errors and the order of the columns was broken

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-webcomponents#957]
## Description  
Resizing the width of the `IgcGrid` from scrolling to the right caused errors, and the order of the columns was broken.

## Steps to reproduce  

1. Shrink the width of the `IgcGrid`.
2. Scroll to the right of the scrolling area of the `IgcGrid`.
3. Widen the width of the `IgcGrid`. 

## Result  
Some errors were reported in the browser's dev console. And the order of the columns was broken.

## Expected result  
Nothing should happen.

## Attachments  

See also the video below.

https://github.com/IgniteUI/igniteui-webcomponents/assets/102948935/b750c24b-2c53-47f5-b176-1b8549857241

The project that can reproduce this issue is below.

[📦c-00233215-html-app1.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/12996123/c-00233215-html-app1.zip)

**Comment by jsakamotoIGJP** [comment]
P.S. 
Issue #952 might be involved with this issue each other.

**Comment by ChronosSF** [comment]
@dkamburov , 99% duplicate with #952
